version: '3.8'

services:
  db:
    ports:
      - "5432:5432"

  turns-service:
    volumes:
      - ../../services/turns:/app
    environment:
      - DEBUG=true

  agents-service:
    volumes:
      - ../../services/agents:/app
    environment:
      - DEBUG=true

  reporting-service:
    volumes:
      - ../../services/reporting:/app
    environment:
      - DEBUG=true